const data = {
  products: [
    {
      name: 'Ross308',
      slug: 'Ross397',
      Category: 'Live Stock',
      image: '/img/image-0.jpeg', // 679 x 829
      currency: 'R',
      tag: 'DayOldChick',
      price: 20,
      discount: 5,
      currentPrice: 15,
      countInStock: 10,
      brand: 'Ross308',
      rating: 4.5,
      numReviews: 13,
      description: 'Ross308 Day Old Chicks and more information',
    },
    {
      name: 'Ross308 Day',
      slug: 'Ross308',
      Category: 'Live Stock',
      image: '/img/image-4.jpeg',
      currency: 'R',
      tag: 'DayOldChick',
      price: 900,
      discount: 200,
      currentPrice: 700,
      countInStock: 30,
      brand: 'Ross308',
      rating: 4.3,
      numReviews: 3,
      description: '',
    },
    {
      name: 'Ross308 Chick',
      slug: 'Ross311',
      Category: 'Live Stock',
      image: '/img/Image-2.jpeg',
      currency: 'R',
      tag: 'DayOldChick',
      price: 1200,
      discount: 300,
      currentPrice: 1500,
      countInStock: 21,
      brand: 'Ross308',
      rating: 4.7,
      numReviews: 22,
      description: '',
    },
    {
      name: 'Ross1414 Marber Chick',
      slug: 'Ross1414',
      Category: 'Live Stock',
      image: '/img/Image-3.jpeg',
      currency: 'R',
      tag: 'Ross1414Chick',
      price: 1200,
      discount: 300,
      currentPrice: 900,
      countInStock: 11,
      brand: 'Ross1414',
      rating: 4.8,
      numReviews: 8,
      description: '',
    },
  ],
};

export default data;
